/// Flutter icons OzoneDiaicon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OzoneDiaicon
///      fonts:
///       - asset: fonts/OzoneDiaicon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OzoneDiaicon {
  OzoneDiaicon._();

  static const _kFontFam = 'OzoneDiaicon';
  static const _kFontPkg = null;

  static const IconData round = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asscher = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cushion = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emerald = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData marquise = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oval = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pear = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData princess = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radiant = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData all = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData other = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
